### ISSUE TITLE
Fail to compile with ghc >= 7.8

### ISSUE THREAD

**Issue by acieroid** [m4dc4p/haskelldb#20]
HaskellDB does not compile anymore with recent versions of GHC.

```
src/Database/HaskellDB/Query.hs:803:10: Warning:
    ‘Query’ is an instance of Monad but not Applicative - this will become an error in GHC 7.10, under the Applicative-Monad Proposal.
[11 of 27] Compiling Database.HaskellDB.FieldType ( src/Database/HaskellDB/FieldType.hs, dist/build/Database/HaskellDB/FieldType.o )

src/Database/HaskellDB/FieldType.hs:84:5:
    ‘typeOf’ is not a (visible) method of class ‘Typeable’

src/Database/HaskellDB/FieldType.hs:84:28:
    Not in scope: ‘mkTyCon’
    Perhaps you meant ‘mkTyCon3’ (imported from Data.Dynamic)

src/Database/HaskellDB/FieldType.hs:87:5:
    ‘typeOf’ is not a (visible) method of class ‘Typeable’

src/Database/HaskellDB/FieldType.hs:87:28:
    Not in scope: ‘mkTyCon’
    Perhaps you meant ‘mkTyCon3’ (imported from Data.Dynamic)
```

Typeable has changed in GHC 7.8 and instances cannot be defined anymore. They
should instead be derivated. It shouldn't be a problem for BoundedString, which
definition is part of HaskellDB. However, for CalendarTime it is problematic,
as CalendarTime is provided by an (deprecated) external library (old-time's
System.Time, which is superseded by time's Data.Time).

I don't have much idea how to fix this, but should anyone give a hint, I would
be glad to help.
